apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: canary-check
spec:
  args:
  - name: host
  metrics:
  - name: canary-check
    failureLimit: 1
    interval: 1
    successCondition: result == "ok"
    provider:
      web:
        # paceholders are resolved when an AnalysisRun is created
        url: "http://{{args.host}}/"
        # url: "http://34.100.195.123"
        jsonPath: "{$.status}"

 # This file contains AnalysisTemplates referenced by Rollouts and Experiments in the examples.
# # Please apply this file first, before running any of the examples.

# ---
# # This AnalysisTemplate will run a Kubernetes Job every 5 seconds that succeeds.
# kind: AnalysisTemplate
# apiVersion: argoproj.io/v1alpha1
# metadata:
#   name: pass
# spec:
#   metrics:
#   - name: pass
#     count: 1
#     interval: 5s
#     failureLimit: 1
#     provider:
#       job:
#         spec:
#           backoffLimit: 1
#           template:
#             spec:
#               containers:
#               - name: sleep
#                 image: alpine:3.8
#                 command: [sh, -c]
#                 args: [pass]
#               restartPolicy: Never


# ---
# # This AnalysisTemplate will run a Kubernetes Job every 10 seconds, with a 50% chance of failure.
# # When the number of accumulated failures exceeds failureLimit, it will cause the analysis run to
# # fail, and subsequently cause the rollout or experiment to abort.
# kind: AnalysisTemplate
# apiVersion: argoproj.io/v1alpha1
# metadata:
#   name: random-fail
# spec:
#   metrics:
#   - name: random-fail
#     count: 2
#     interval: 10s
#     failureLimit: 1
#     provider:
#       job:
#         spec:
#           backoffLimit: 1
#           template:
#             spec:
#               containers:
#               - name: sleep
#                 image: alpine:3.8
#                 command: [sh, -c]
#                 args: [random-fail]
#               restartPolicy: Never
