apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: argorollout-canaryanalysis
spec:
  replicas: 5
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 5}
      - analysis:
          templates:
          - templateName: canarycheck
      # - args:
      #   - name: host
      #     value: rollouts-demo
          # args:
          # - name: host
          #   value: argorollout-canaryanalysis
      - setWeight: 40
      - pause: {duration: 5}
      - setWeight: 60
      - pause: {duration: 5}
      - setWeight: 80
      - pause: {duration: 5}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: argorollout-canaryanalysis
  template:
    metadata:
      labels:
        app: argorollout-canaryanalysis
    spec:
      containers:
      - name: argorollout-canaryanalysis
        # image: argoproj/rollouts-demo:black
        image: particule/simplecolorapi:3.0
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m


# apiVersion: argoproj.io/v1alpha1
# kind: Rollout
# metadata:
#   name: argorollout-canaryanalysis
# spec:
#   replicas: 5
#   strategy:
#     canary:
#       steps:
#       - setWeight: 20
#       - pause: {duration: 10}
#       - analysis:
#           templates:
#           - templateName: canarycheck
#       # - args:
#       #   - name: host
#       #     value: rollouts-demo
#           # args:
#           # - name: host
#           #   value: argorollout-canaryanalysis
#       - setWeight: 40
#       - pause: {duration: 10}
#       - setWeight: 60
#       - pause: {duration: 10}
#       - setWeight: 80
#       - pause: {duration: 10}
#   revisionHistoryLimit: 2
#   selector:
#     matchLabels:
#       app: argorollout-canaryanalysis
#   template:
#     metadata:
#       labels:
#         app: argorollout-canaryanalysis
#     spec:
#       containers:
#       - name: argorollout-canaryanalysis
#         image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
#         # image: particule/simplecolorapi:1.0
#         ports:
#         - name: http
#           containerPort: 5000
#           protocol: TCP
#         resources:
#           requests:
#             memory: 32Mi
#             cpu: 5m


# apiVersion: argoproj.io/v1alpha1
# kind: Rollout
# metadata:
#   name: argorollout-canaryanalysis
# spec:
#   replicas: 5
#   strategy:
#     canary:
#       steps:
#       - setWeight: 20
#       - pause: {duration: 10}
#       - analysis:
#           templates:
#           # - templateName: pass
#           - templateName: random-fail
#       - setWeight: 40
#       - pause: {duration: 10}
#       - setWeight: 60
#       - pause: {duration: 10}
#       - setWeight: 80
#       - pause: {duration: 10}
#   revisionHistoryLimit: 2
#   selector:
#     matchLabels:
#       app: argorollout-canaryanalysis
#   template:
#     metadata:
#       labels:
#         app: argorollout-canaryanalysis
#     spec:
#       containers:
#       - name: argorollout-canaryanalysis
#         image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
#         ports:
#         - name: http
#           containerPort: 8080
#           protocol: TCP
#         resources:
#           requests:
#             memory: 32Mi
#             cpu: 5m